services:

  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: itm-database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - itm-network

  api-gestion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itm-api
    depends_on:
      - db-sqlserver
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db-sqlserver;Database=GestionITM;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - JWT_KEY=${JWT_KEY}
      - Jwt__Issuer=GestionITMAPI
      - Jwt__Audience=EstudiantesITM
    networks:
      - itm-network

networks:
  itm-network:
    driver: bridge

volumes:
  sqlserver_data:
