services: 

  # ----------------------------------------------------
  # CAMIÓN 1: La Base de Datos (SQL Server para Linux)
  # ----------------------------------------------------
  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: itm-database
    environment:
      - ACCEPT_EULA=Y
      # La contraseña se inyecta desde la variable DB_PASSWORD declarada en el archivo .env
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433" # Mapeamos el puerto de SQL Server
    networks:
      - itm-network

  # ----------------------------------------------------
  # CAMIÓN 2: Nuestra API de Matrículas y Cursos
  # ----------------------------------------------------
  api-gestion:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: itm-api
    depends_on:
      - db-sqlserver # La API no arranca si la BD no está lista
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # La contraseña de la cadena de conexión se lee de forma dinámica desde el entorno
      - 'ConnectionStrings__DefaultConnection=Server=db-sqlserver;Database=GestionITM;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;'
    networks:
      - itm-network

# Red interna privada para que los contenedores se comuniquen
networks:
  itm-network:
    driver: bridge
